services:
  influx:
    container_name: influx-testfma
    image: influxdb:1.11
    ports:
      - "8086:8086"
    networks:
      - testfma
    environment:
      INFLUXDB_HTTP_FLUX_ENABLED: true

networks:
  testfma:
    name: testfma
    driver: bridge
